name: Terraform CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run a Terraform init
      uses: docker://hashicorp/terraform:1.0.4
      with:
        entrypoint: terraform
        args: init

    - name: Run a Terraform validate
      uses: docker://hashicorp/terraform:1.0.4
      with:
        entrypoint: terraform
        args: validate

    - name: Run a Terraform plan
      uses: docker://hashicorp/terraform:1.0.4
      with:
        entrypoint: terraform
        args: plan

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Get dependencies
      run: |
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        else
          go get -v -t -d ./...
        fi

    - name: Test
      working-directory: /home/runner/work/terratest-demo/terratest-demo/test
      run: go test
